"use client";

import { useEffect, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { loadAnalytics, persistAnalytics } from "@/lib/data/analytics";
import type { AnalyticsResult, RankedMetric } from "@/lib/analytics/engine";
import { refreshInsights } from "@/lib/data/insights";
import type { GroundedInsight } from "@/lib/ai/synthesise-insights";

const money = (value:number) => new Intl.NumberFormat("en", {style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(value);
const pct = (value:number|null) => value == null ? "N/A" : `${value >= 0 ? "+" : ""}${(value*100).toFixed(1)}%`;

export function MarketDashboard({datasetId, title="Your market analysis"}:{datasetId:string;title?:string}) {
  const [data,setData] = useState<AnalyticsResult>(); const [error,setError] = useState(""); const [tab,setTab] = useState<"categories"|"ingredients"|"products"|"companies"|"channels">("categories");
  const [insights,setInsights]=useState<GroundedInsight[]>([]);
  useEffect(() => { loadAnalytics(datasetId).then(async result => {setData(result); await persistAnalytics(datasetId,result); setInsights(await refreshInsights(datasetId,result));}).catch((e)=>setError(e.message)); },[datasetId]);
  if (error) return <section className="card p-6 text-sm text-amber-800">Analysis needs attention: {error}</section>;
  if (!data) return <section className="card p-6 text-sm text-[var(--muted)]">Computing deterministic market metrics…</section>;
  const table:RankedMetric[] = tab === "categories" ? data.categories : tab === "ingredients" ? data.ingredients : tab === "products" ? data.products : tab === "companies" ? data.corporations : data.channels;
  return <section className="space-y-6" id="dashboard">
    <div className="flex flex-wrap justify-between items-end gap-4"><div><div className="eyebrow">Step 4 · Analyse</div><h2 className="text-3xl font-semibold mt-2">{title}</h2><p className="text-sm text-[var(--muted)] mt-1">Latest comparable period: {data.latestPeriod}</p></div><span className="status-pill status-good">Engine computed</span></div>
    <div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Kpi label="Latest market value" value={money(data.totalValue)} note={data.latestPeriod}/><Kpi label="Quarterly growth" value={pct(data.qoq)} note={data.previousPeriod ? `vs ${data.previousPeriod}`:"Insufficient baseline"}/><Kpi label="Yearly growth" value={pct(data.yoy)} note={data.yoyPeriod ? `vs ${data.yoyPeriod}`:"Needs prior year"}/><Kpi label="Portfolio share" value={`${(data.portfolioShare*100).toFixed(1)}%`} note={money(data.portfolioValue)}/></div>
    <div className="grid xl:grid-cols-[1.4fr_.8fr] gap-5"><div className="card p-5"><div className="font-semibold">Quarterly market trajectory</div><div className="text-xs text-[var(--muted)] mt-1">Total market and confirmed portfolio</div><div className="h-72 mt-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trend}><defs><linearGradient id="market" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#0b6b50" stopOpacity={.35}/><stop offset="1" stopColor="#0b6b50" stopOpacity={.03}/></linearGradient></defs><CartesianGrid stroke="#e5ebe7" vertical={false}/><XAxis dataKey="period" tick={{fontSize:11}}/><YAxis tickFormatter={(v)=>money(v)} tick={{fontSize:10}} width={70}/><Tooltip formatter={(v)=>money(Number(v))}/><Area dataKey="value" type="monotone" stroke="#0b6b50" fill="url(#market)" strokeWidth={3}/><Area dataKey="portfolio" type="monotone" stroke="#d38a34" fill="transparent" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div><div className="card p-5"><div className="eyebrow">Opportunity ranking</div><div className="mt-4 space-y-4">{data.categories.slice(0,5).map((item)=><div key={item.id}><div className="flex justify-between gap-3 text-sm"><span className="font-semibold">#{item.rank} {item.name}</span><span>{Math.round(item.opportunityScore*100)}</span></div><div className="h-2 bg-[#e8eeea] rounded mt-2 overflow-hidden"><div className="h-full bg-[#72a673]" style={{width:`${item.opportunityScore*100}%`}}/></div><div className="text-[11px] text-[var(--muted)] mt-1">{pct(item.growth)} growth · {(item.portfolioShare*100).toFixed(1)}% portfolio share</div></div>)}</div></div></div>
    <div className="card"><div className="p-5 flex flex-wrap gap-2 border-b border-[var(--line)]">{(["categories","ingredients","products","companies","channels"] as const).map((item)=><button key={item} className={tab===item?"btn-primary":"btn-secondary"} onClick={()=>setTab(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div><div className="table-wrap"><table><thead><tr><th>Rank</th><th>{tab.slice(0,-1)}</th><th>Latest value</th><th>Market share</th><th>QoQ growth</th><th>Share change</th></tr></thead><tbody>{table.slice(0,20).map((item)=><tr key={item.name}><td>#{item.rank}</td><td className="font-semibold">{item.name}</td><td>{money(item.value)}</td><td>{(item.share*100).toFixed(1)}%</td><td className={(item.growth??0)>=0?"text-emerald-700":"text-red-700"}>{pct(item.growth)}</td><td>{item.shareChange==null?"N/A":`${(item.shareChange*100).toFixed(1)} pp`}</td></tr>)}</tbody></table></div></div>
    <div className="grid xl:grid-cols-2 gap-5" id="competitive"><div className="card p-5"><div className="eyebrow">Competitive intelligence</div><h3 className="text-xl font-semibold mt-2">Portfolio-category threats</h3><div className="mt-4 space-y-3">{data.threats.slice(0,6).map((item)=><div key={`${item.categoryId}-${item.corporation}`} className="rounded-xl border border-[var(--line)] p-4 flex justify-between gap-4"><div><div className="font-semibold text-sm">{item.corporation}</div><div className="text-xs text-[var(--muted)] mt-1">{item.category} · {pct(item.growth)} growth</div></div><div className="text-right"><span className={`status-pill ${item.level==="High"?"status-warn":"status-good"}`}>{item.level}</span><div className="text-xs mt-2">{item.shareChange==null?"N/A":`${(item.shareChange*100).toFixed(1)} pp`}</div></div></div>)}{!data.threats.length&&<p className="text-sm text-[var(--muted)]">No comparable competitor movement is available.</p>}</div></div><div className="card p-5" id="insights"><div className="eyebrow">Step 5 · Explain</div><h3 className="text-xl font-semibold mt-2">Grounded strategic signals</h3><div className="mt-4 space-y-3">{insights.map((item,index)=><article key={`${item.type}-${index}`} className="rounded-xl bg-[#f5f7f4] p-4"><div className="flex justify-between gap-3"><span className="status-pill status-good">{item.signal}</span><span className="text-xs text-[var(--muted)]">{Math.round(item.confidence*100)}% confidence</span></div><p className="font-semibold text-sm mt-3 leading-relaxed">{item.summary}</p><p className="text-xs text-[var(--muted)] mt-2 leading-relaxed">{item.interpretation}</p><details className="mt-3"><summary className="text-xs font-bold text-[var(--green)] cursor-pointer">Why am I seeing this?</summary><div className="mt-2 rounded-lg bg-white border border-[var(--line)] p-3"><dl className="grid grid-cols-2 gap-2">{Object.entries(item.evidence).map(([key,value])=><div key={key}><dt className="text-[10px] uppercase text-[var(--muted)]">{key.replaceAll("_"," ")}</dt><dd className="text-xs font-semibold break-all">{value==null?"N/A":typeof value==="number"?Number(value.toFixed(4)):value}</dd></div>)}</dl><p className="text-xs mt-3"><strong>Investigate:</strong> {item.investigation}</p></div></details></article>)}</div></div></div>
  </section>;
}
function Kpi({label,value,note}:{label:string;value:string;note:string}) {return <div className="card p-5"><div className="text-xs text-[var(--muted)]">{label}</div><div className="text-3xl font-semibold mt-2">{value}</div><div className="text-xs text-[var(--muted)] mt-2">{note}</div></div>}
